@startuml
|User|
|Frontend|
|Backend|

|User|
start
:1 Select notification to read;
|Frontend|
:2 Validate input information;
if (Valid?) then (Yes)
  |Backend|
  :3.1 Query notification detail;
  if (Found?) then (Yes)
    |Frontend|
    :4.1 Display notification detail;
    |User|
    :5.1 Confirm success notification;
    stop
  else (No)
    |Frontend|
    :4.2 Notify notification not found;
    |User|
    :5.2 Confirm error notification;
    end
  endif
else (No)
  |Frontend|
  :3.2 Notify invalid input;
  |User|
  :4.3 Confirm error notification;
  end
endif
@enduml