@startuml
|User|
|Frontend|
|Backend|

|User|
start
:1 Select post to moderate;
|Backend|
:2 Query existing post;
if (Exists?) then (Yes)
  |Frontend|
  :3.1 Display existing data;
  |User|
  :4.1 Select moderation decision;
  :5.1 Click button "Moderate";
  |Frontend|
  :6.1 Validate input information;
  if (Valid?) then (Yes)
    |Backend|
    :7.1 Validate post data;
    if (Valid?) then (Yes)
      :8.1 Update post status;
      |Frontend|
      :9.1 Notify moderation success;
      |User|
      :10.1 Confirm success notification;
      stop
    else (No)
      |Frontend|
      :8.2 Notify invalid data;
      |User|
      :9.2 Confirm error notification;
      end
    endif
  else (No)
    |Frontend|
    :7.2 Notify invalid input;
    |User|
    :8.3 Confirm error notification;
    end
  endif
else (No)
  |Frontend|
  :3.2 Notify post not found;
  |User|
  :4.2 Confirm error notification;
  end
endif
@enduml