@startuml
|User|
|Frontend|
|Backend|

|User|
start
:1 Click button "Save";
|Frontend|
:2 Validate input information;
if (Valid?) then (Yes)
  |Backend|
  :3.1 Validate post data;
  if (Valid?) then (Yes)
    :4.1 Store saved post;
    :5.1 Notify save success;
    |User|
    :6.1 Confirm success notification;
    stop
  else (No)
    |Backend|
    :4.2 Notify invalid post;
    |User|
    :5.2 Confirm error notification;
    end
  endif
else (No)
  |Frontend|
  :3.2 Notify invalid input;
  |User|
  :4.3 Confirm error notification;
  end
endif
@enduml