@startuml
|User|
|Frontend|
|Backend|

|User|
start
:1 Click button "Unsave";
|Frontend|
:2 Display confirmation message;
|User|
if (Confirm?) then (Yes)
  :3.1 Click button "Confirm";
  |Backend|
  :4.1 Validate saved post;
  if (Exists?) then (Yes)
    :5.1 Delete saved post;
    :6.1 Notify unsave success;
    |User|
    :7.1 Confirm success notification;
    stop
  else (No)
    |Backend|
    :5.2 Notify invalid record;
    |User|
    :6.2 Confirm error notification;
    end
  endif
else (No)
  |User|
  :3.2 Click button "Cancel";
  end
endif
@enduml